version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: progra3card_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "mi_banco_db"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mi_banco_db.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: progra3card_web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

volumes:
  db_data:
